# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'try {} caugh'
tagline:          '@pdorofiejczyk`s dev blog'
url:              http://pdorofiejczyk.github.io
paginate:         1
baseurl:          /
author:
  name:           Paweł Dorofiejczyk
  url:            https://twitter.com/pdorofiejczyk
  email:          pawel.dorofiejczyk@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
